apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 80        # Port exposed on the service
      targetPort: 80   # Port the service forwards traffic to on the pod
      nodePort: 30081  # Exposed NodePort
